# Generated by Django 3.1.3 on 2020-12-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_summary', '0027_auto_20201227_1811'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_added', models.DateField(auto_now_add=True)),
                ('i_watching', models.BooleanField()),
                ('i_owned', models.BooleanField()),
                ('q_shares_owned', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('a_share_price_bought', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('a_invested', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_summary.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'stock__t_short_name'],
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='UserStockAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_alert', models.DateField(auto_now_add=True)),
                ('t_alert', models.CharField(max_length=100)),
                ('userStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userstock')),
            ],
        ),
    ]
