# Generated by Django 3.1.3 on 2021-01-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0033_auto_20201230_1509'),
        ('registration', '0003_auto_20201229_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='a_invested',
        ),
        migrations.RemoveField(
            model_name='userstock',
            name='a_share_price_bought',
        ),
        migrations.RemoveField(
            model_name='userstock',
            name='i_owned',
        ),
        migrations.RemoveField(
            model_name='userstock',
            name='i_watching',
        ),
        migrations.RemoveField(
            model_name='userstock',
            name='q_shares_owned',
        ),
        migrations.CreateModel(
            name='UserStockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_transaction', models.DateTimeField()),
                ('c_type', models.CharField(max_length=2)),
                ('q_shares', models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True)),
                ('a_share_price', models.DecimalField(decimal_places=3, default=0, max_digits=8, null=True)),
                ('a_invested', models.DecimalField(decimal_places=3, default=0, max_digits=8, null=True)),
                ('t_notes', models.CharField(max_length=100)),
                ('stockeodprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_summary.stockeodprofile')),
                ('userstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.userstock')),
            ],
            options={
                'ordering': ['s_transaction', 'userstock__user__username'],
                'unique_together': {('userstock', 's_transaction')},
            },
        ),
    ]
