# Generated by Django 3.1.3 on 2021-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210103_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='c_type',
            field=models.CharField(default='W', max_length=2),
            preserve_default=False,
        ),
    ]
