# Generated by Django 3.1.3 on 2021-01-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userstock_c_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='a_invested',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='userstock',
            name='q_shares_owned',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
