# Generated by Django 3.1.3 on 2021-01-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_userstocktransaction_d_executed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='c_type',
        ),
        migrations.RemoveField(
            model_name='userstocktransaction',
            name='c_type',
        ),
        migrations.AddField(
            model_name='userstock',
            name='t_stock_type',
            field=models.CharField(default='W', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstocktransaction',
            name='t_transaction_type',
            field=models.CharField(default='MOCK BUY', max_length=10),
            preserve_default=False,
        ),
    ]
