# Generated by Django 3.1.3 on 2021-01-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0033_auto_20201230_1509'),
        ('registration', '0011_auto_20210104_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocktransaction',
            name='stockeodprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_summary.stockeodprofile'),
        ),
    ]
