# Generated by Django 3.1.3 on 2021-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20210104_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocktransaction',
            name='a_invested',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userstocktransaction',
            name='a_share_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userstocktransaction',
            name='q_shares',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
