# Generated by Django 3.1.3 on 2021-01-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0014_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_summary_pg_alerts_open', models.BooleanField()),
                ('i_summary_pg_trans_open', models.BooleanField()),
                ('i_summary_pg_port_open', models.BooleanField()),
                ('i_expert_rec_send_email', models.BooleanField()),
                ('i_expert_rec_send_text', models.BooleanField()),
                ('i_expert_rec_buy', models.BooleanField()),
                ('i_expert_rec_sell', models.BooleanField()),
                ('i_expert_rec_other', models.BooleanField()),
                ('i_custom_alerts_send_email', models.BooleanField()),
                ('i_custom_alerts_send_text', models.BooleanField()),
                ('i_custom_alerts_buy', models.BooleanField()),
                ('i_custom_alerts_sell', models.BooleanField()),
                ('i_custom_alerts_other', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
