# Generated by Django 3.1.3 on 2021-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20210114_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='i_summary_pg_alerts_open',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='i_summary_pg_port_open',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='i_summary_pg_trans_open',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
