# Generated by Django 3.1.3 on 2020-11-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_summary', '0015_auto_20201130_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_alert', models.DateField(auto_now_add=True)),
                ('t_alert', models.CharField(max_length=100)),
                ('d_closed', models.DateField(null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_summary.stock')),
            ],
        ),
    ]
