# Generated by Django 3.1.3 on 2020-12-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0002_auto_20201130_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_page_order', models.SmallIntegerField()),
                ('t_short_name', models.CharField(max_length=3)),
                ('t_long_name', models.CharField(max_length=25)),
                ('q_days', models.SmallIntegerField()),
                ('i_active', models.BooleanField()),
            ],
        ),
    ]
