# Generated by Django 3.1.3 on 2020-12-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0003_chartinterval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartinterval',
            options={'ordering': ['q_days']},
        ),
    ]
