# Generated by Django 3.1.3 on 2020-12-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0026_sectorindustryperformance'),
        ('stock_analysis', '0004_auto_20201214_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_evaluated', models.DateField()),
                ('q_aj_trader_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('a_one_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_two_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_three_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_four_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_five_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_six_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_seven_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_two_week_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_three_week_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_two_month_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_three_month_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_avg_volume', models.IntegerField()),
                ('q_consecutive_days_down', models.SmallIntegerField()),
                ('q_consecutive_days_up', models.SmallIntegerField()),
                ('a_close_to_fifty_two_week_high_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_close_to_fifty_two_week_low_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('userstock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_summary.userstock')),
            ],
        ),
        migrations.CreateModel(
            name='UserStockProfileAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_alert', models.DateField(auto_now_add=True)),
                ('t_alert', models.CharField(max_length=100)),
                ('userstockprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.userstockprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='StockAlert',
        ),
    ]
