# Generated by Django 3.1.3 on 2020-12-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0005_auto_20201227_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstockprofilealert',
            name='userstockprofile',
        ),
        migrations.DeleteModel(
            name='UserStockProfile',
        ),
        migrations.DeleteModel(
            name='UserStockProfileAlert',
        ),
    ]
