# Generated by Django 3.1.3 on 2020-11-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_symbol', models.CharField(max_length=5, unique=True)),
                ('c_exchange', models.CharField(max_length=5)),
                ('t_sector', models.CharField(max_length=40)),
                ('t_industry', models.CharField(max_length=40)),
                ('t_short_name', models.CharField(max_length=20)),
                ('t_long_name', models.CharField(max_length=40)),
                ('t_website_url', models.CharField(max_length=40)),
                ('t_logo_url', models.CharField(max_length=40)),
                ('a_full_time_employees', models.SmallIntegerField()),
                ('c_state', models.CharField(max_length=2)),
                ('i_aj_owns', models.BooleanField()),
            ],
        ),
    ]
