# Generated by Django 3.1.3 on 2020-11-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='a_full_time_employees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='t_long_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='stock',
            name='t_short_name',
            field=models.CharField(max_length=40),
        ),
    ]
