# Generated by Django 3.1.3 on 2020-11-25 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0002_auto_20201124_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='i_aj_owns',
        ),
        migrations.CreateModel(
            name='StockWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_added', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_summary.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_added', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_summary.stock')),
            ],
        ),
    ]
