# Generated by Django 3.1.3 on 2020-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0005_stockdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='t_industry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='t_logo_url',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='stock',
            name='t_long_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='stock',
            name='t_sector',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='t_short_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='t_website_url',
            field=models.CharField(max_length=60),
        ),
    ]
