# Generated by Django 3.1.3 on 2020-11-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0006_auto_20201125_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockDaily',
            new_name='StockEOD',
        ),
    ]
