# Generated by Django 3.1.3 on 2020-11-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0007_auto_20201125_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockeod',
            old_name='a_ten_day_vol_avg',
            new_name='a_ten_day_volume_avg',
        ),
    ]
