# Generated by Django 3.1.3 on 2020-11-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0011_stockeod_a_previous_close_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockeod',
            old_name='a_previous_close_change',
            new_name='a_close_change',
        ),
        migrations.AddField(
            model_name='stockeod',
            name='a_close',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
