# Generated by Django 3.1.3 on 2020-11-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0012_auto_20201128_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='d_added',
            field=models.DateField(auto_now_add=True, default='2020-11-29'),
            preserve_default=False,
        ),
    ]
