# Generated by Django 3.1.3 on 2020-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0013_stock_d_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='q_shares_owned',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
