# Generated by Django 3.1.3 on 2020-11-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0014_stock_q_shares_owned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockeod',
            options={'ordering': ['-d_process', 'stock__n_symbol']},
        ),
    ]
