# Generated by Django 3.1.3 on 2020-12-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0015_auto_20201130_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockeod',
            old_name='a_close_change',
            new_name='a_close_delta',
        ),
        migrations.AddField(
            model_name='stockeod',
            name='a_open_close_delta',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
