# Generated by Django 3.1.3 on 2020-12-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0016_auto_20201204_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='q_shares_owned',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
