# Generated by Django 3.1.3 on 2020-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0018_auto_20201217_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='a_share_price_bought',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='q_shares_owned',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
