# Generated by Django 3.1.3 on 2020-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0022_auto_20201218_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockeod',
            name='a_market_cap',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_payout_ratio',
            field=models.IntegerField(null=True),
        ),
    ]
