# Generated by Django 3.1.3 on 2020-12-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0024_auto_20201218_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstock',
            options={'ordering': ['user__username', 'stock__t_short_name']},
        ),
    ]
