# Generated by Django 3.1.3 on 2020-12-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0025_auto_20201227_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorIndustryPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_sector', models.CharField(max_length=50)),
                ('t_industry', models.CharField(max_length=50)),
                ('d_evaluated', models.DateField()),
                ('a_forward_eps', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('a_trailing_eps', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
            ],
        ),
    ]
