# Generated by Django 3.1.3 on 2020-12-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0006_auto_20201227_1811'),
        ('stock_summary', '0026_sectorindustryperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEODProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_evaluated', models.DateField()),
                ('q_aj_trader_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('a_one_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_two_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_three_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_four_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_five_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_six_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_seven_day_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_two_week_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_three_week_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_two_month_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_three_month_close_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_avg_volume', models.IntegerField()),
                ('q_consecutive_days_down', models.SmallIntegerField()),
                ('q_consecutive_days_up', models.SmallIntegerField()),
                ('a_close_to_fifty_two_week_high_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('a_close_to_fifty_two_week_low_delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('stockEOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_summary.stockeod')),
            ],
        ),
        migrations.DeleteModel(
            name='UserStock',
        ),
    ]
