# Generated by Django 3.1.3 on 2020-12-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0027_auto_20201227_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockeodprofile',
            old_name='d_evaluated',
            new_name='d_evaluation',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_high_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_low_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_five_day_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_four_day_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_one_day_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_seven_day_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_six_day_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_three_day_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_three_month_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_three_week_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_two_day_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_two_month_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='a_two_week_close_delta',
        ),
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='q_consecutive_days_up',
        ),
        migrations.AddField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_high',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_low',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockeodprofile',
            name='q_percent_change',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
