# Generated by Django 3.1.3 on 2020-12-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0028_auto_20201229_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockeodprofile',
            old_name='stockEOD',
            new_name='stockeod',
        ),
    ]
