# Generated by Django 3.1.3 on 2020-12-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0030_auto_20201229_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockeodprofile',
            name='q_aj_trader_score',
        ),
        migrations.AddField(
            model_name='stockeodprofile',
            name='t_status',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
