# Generated by Django 3.1.3 on 2020-12-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0032_auto_20201229_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_high',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_low',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
