# Generated by Django 3.1.3 on 2021-01-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0036_auto_20210113_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecommendation',
            name='t_action',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stockrecommendation',
            unique_together={('stock', 's_recommendation', 't_firm', 't_to_grade', 't_from_grade', 't_action')},
        ),
    ]
