# Generated by Django 3.1.3 on 2021-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0037_auto_20210113_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorindustryperformance',
            name='a_forward_eps',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sectorindustryperformance',
            name='a_trailing_eps',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_ask',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_beta',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_bid',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_close',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_close_delta',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_fifty_two_week_delta',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_fifty_two_week_high',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_fifty_two_week_low',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_forward_eps',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_high',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_low',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_low_high_delta',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_open',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_open_close_delta',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_previous_close',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_trailing_eps',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_high',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='a_close_to_fifty_two_week_low',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='a_consecutive_days_price_change',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='q_consecutive_days_percent_change',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='q_consecutive_days_volume_percent_change',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
