# Generated by Django 3.1.3 on 2021-04-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_summary', '0038_auto_20210402_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='a_full_time_employees',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_avg_volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_ten_day_volume_avg',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='a_volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='q_ask_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeod',
            name='q_bid_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='a_avg_volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockeodprofile',
            name='a_consecutive_days_volume_change',
            field=models.BigIntegerField(),
        ),
    ]
